CustomerIdPath:
  name: id
  in: path
  required: true
  description: Identificador do cliente
  schema:
    type: integer
    format: int64
    minimum: 1
  example: 10

PageParam:
  name: page
  in: query
  required: false
  description: Índice da página (0-based)
  schema:
    type: integer
    minimum: 0
    default: 0
  example: 0

SizeParam:
  name: size
  in: query
  required: false
  description: Tamanho da página (> 0)
  schema:
    type: integer
    minimum: 1
    default: 20
  example: 20

SortParam:
  name: sort
  in: query
  required: false
  description: >
    Ordenação no padrão Spring Data.
    Pode ser repetido múltiplas vezes. Ex.: `sort=name,asc&sort=email,desc`
  schema:
    type: array
    items:
      type: string
  style: form
  explode: true
  example: ["name,asc", "email,desc"]
